### ISSUE TITLE
Naming could be offensive

### ISSUE THREAD

**Issue by NoelAbrahams** [fetlang/fetlang#10]
The following is offensive IMO on account of the choice of occidental first names.
```
lick Ada's feet forty three times
lick Sasha's left nipple forty five times
lick Leo's balls sixty times
lick Randy's cock sixty two times
lick Wendy's asshole ninety one times
lick Ender's belly ninety three times
lick Orange's nose forty six times
lick Inky's forehead forty four times
```

Suggestions:
`lick Ahmed's balls sixty times` or
`lick Meera's left nipple forty five times`

**Comment by Kaos-Industries** [comment]
Are you... being serious?

**Comment by Two-Finger** [comment]
Absolutely!
How come 王秀英 hasn't been mentioned?

**Comment by NLDev** [comment]
> Since when occidental first names have became offensive ?

Everything is offensive nowadays I guess...

**Comment by spacekookie** [comment]
I mean...including names that aren't occidental isn't per say a bad thing. But calling it offensive is a bit of a stretch

**Comment by DanielMReed** [comment]
Bait issue, if not, ignore it anyway. It's fetlang, it's not exactly a PC thing

**Comment by lychaxo** [comment]
Honestly I opened this issue up, expecting it to be the reason behind commit da418aec3eef441c78f7f4de02b15a28cb937bb2, given the timing -- which I'm still curious about

**Comment by fetlang** [comment]
@lychaxo It's completely unrelated to this not-really-all-that-funny-and-honestly-kinda-obvious troll attempt.

Regarding that commit, the replacement word is more light hearted, inoffensive, funnier(IMO), and better suits the feel of Fetlang, which was intended to be light-hearted, relatively inoffensive, and funny. I felt that the "cunt," which is a fairly harsh word to American ears, went a little overboard from that ideal. There was no outside pressure to change the wording. The "PC Police" did not get me.

The comment section is closed because people were writing dumb-ass comments, including implications that talking about sex is inherently "anti-PC." Not unlike @DanielRX's comment above yours.

While I'm on the subject, I would also like to state that Fetlang was never meant to be "anti-PC," as some seemed to joyously have interpreted it. For some reason, it seems a lot of that crowd have this idea that dirty humour is somehow incompatible with progressivism, or that telling a dirty joke is "sticking it to the feminists" or whatever.

To my knowledge, nobody has actually expressed being offended by Fetlang, outside of some pedants who insisted there was a very important difference between "fetishes" and "kinks," and those who thought my esoteric language was not esoteric enough.

I know that was bit of a rant, but hopefully, this comment will offer some insight and serve as an invitation for everybody to shut the fuck up and get off my dick about this commit.

God bless.
